name = "Quadriceps"
uuid = "9371e607-b390-4342-8322-9e25c25d5a03"
version = "0.1.0"
authors = ["Joris Pinkse <pinkse@gmail.com>"]

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"

[compat]
FastGaussQuadrature = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
